# Created by: iblis <iblis@hs.ntnu.edu.tw>
# $FreeBSD$

PORTNAME=	unittest-cpp
PORTVERSION=	1.6.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel
MASTER_SITES=	GH

MAINTAINER=	iblis@abeing
COMMENT=	Lightweight unit testing framework for C++

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USE_GITHUB=	yes
GH_ACCOUNT=	unittest-cpp
GH_PROJECT=	unittest-cpp

USES=		cmake

.include <bsd.port.mk>
